### ISSUE TITLE
apk文件比较大，大约2.34G，然后就报错了，怎么解决文件很大的apk问题呢？

### ISSUE THREAD

**Issue by javaqiang** [Tencent/VasDolly#128]
java -jar VasDolly.jar put -c "channel1,channel2" ActionRPG-arm64.apk output
find V2 signature block Id : 1896449818
baseApk : C:\Users\jackie\Desktop\1\ActionRPG-arm64.apk , ChannelPackageMode : V2 Mode , isFastMode : false
------ File ActionRPG-arm64.apk generate v2 channel apk  , begin ------
generateV2ChannelApk error , please check it and fix it ，and that you should generate all V2 Channel Apk again!
java.lang.IllegalArgumentException
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:334)
        at com.tencent.vasdolly.common.V2SchemeUtil.getByteBuffer(V2SchemeUtil.java:205)
        at com.tencent.vasdolly.common.V2SchemeUtil.findContentEntry(V2SchemeUtil.java:200)
        at com.tencent.vasdolly.common.V2SchemeUtil.getApkSectionInfo(V2SchemeUtil.java:159)
        at com.tencent.vasdolly.writer.IdValueWriter.getApkSectionInfo(IdValueWriter.java:275)
        at com.tencent.vasdolly.command.Util.generateV2ChannelApk(Util.java:254)
        at com.tencent.vasdolly.command.Util.writeChannel(Util.java:113)
        at com.tencent.vasdolly.command.Main.main(Main.java:176)
------ File ActionRPG-arm64.apk generate v2 channel apk , end ------
------ total 2 channel apk , cost : 2 ------

**Comment by javaqiang** [comment]
V2SchemeUtil类里ByteBuffer byteBuffer = ByteBuffer.allocate(length); length是个int型值，超出int的大小范围导致的
![image](https://user-images.githubusercontent.com/3114560/152718865-2361ee5b-815b-482f-bda2-d8ece3c04c1c.png)

**Comment by yanyongshan** [comment]
这个apk在什么地方可以下载到吗？

**Comment by d-txy** [comment]
遇到过类似的问题，经排查测试是接入bugly旧版本造成的 classpath 'com.tencent.bugly:symtabfileuploader:latest.release'
换成最新的接入方式后就行了。

**Comment by yanyongshan** [comment]
Util.java中的transferTo使用Bug,已经在3.0.5中解决
