### ISSUE TITLE
com.android.build.api.extension.AndroidComponentsExtension

### ISSUE THREAD

**Issue by nanfengkkkkkkk** [Tencent/VasDolly#145]
Caused by: java.lang.ClassNotFoundException: com.android.build.api.extension.AndroidComponentsExtension
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.tencent.vasdolly.plugin.util.AndroidComponentsExtensionCompat$Companion.getAndroidComponentsExtension(AndroidGradleCompat.kt:84)
	at com.tencent.vasdolly.plugin.VasDollyPlugin.createChannelTask(VasDollyPlugin.kt:77)
	at com.tencent.vasdolly.plugin.VasDollyPlugin.apply(VasDollyPlugin.kt:69)

My gradle tools version is 4.1.0

**Comment by yanyongshan** [comment]
V3.0.4版本已支持Android Gradle Plugin 4.2.0以上版本
