### ISSUE TITLE
命令行打包报错NoSuchMethodError   java版本1.8.0_351

### ISSUE THREAD

**Issue by mlp1995** [Tencent/VasDolly#151]
bangong@bangongdeMac-mini chezhiwang % java -jar VasDolly.jar put -c  360 app_V2.7.2.apk   /Users/bangong/Desktop/android/chezhiwang
start check apk signature mode...
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
begin writing apk channel and apk signature version:V2
baseApk:/Users/bangong/Desktop/android/chezhiwang/guzhangdaquan_V2.7.2.apk
outputDir:/Users/bangong/Desktop/android/chezhiwang
isMultiThread:false
isFastMode:false
------ File guzhangdaquan_V2.7.2.apk generate channel apk  , begin ------
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at com.tencent.vasdolly.common.apk.ZipUtils.findZipEndOfCentralDirectoryRecord(ZipUtils.java:131)
        at com.tencent.vasdolly.common.apk.ZipUtils.findZipEndOfCentralDirectoryRecord(ZipUtils.java:73)
        at com.tencent.vasdolly.common.apk.ApkSigningBlockUtils.getEocd(ApkSigningBlockUtils.java:71)
        at com.tencent.vasdolly.common.V2SchemeUtil.getApkSectionInfo(V2SchemeUtil.java:132)
        at com.tencent.vasdolly.writer.IdValueWriter.getApkSectionInfo(IdValueWriter.java:258)
        at com.tencent.vasdolly.command.Util.generateChannelApk(Util.java:272)
        at com.tencent.vasdolly.command.Util.writeChannel(Util.java:119)
        at com.tencent.vasdolly.command.Main.main(Main.java:176)

**Comment by mlp1995** [comment]
刚刚测试使用3.0.4 版本的可以打包成功

**Comment by yanyongshan** [comment]
你可以先将Java版本升级到Java11，应该就可以用了，我这里尽快修复一下

**Comment by mlp1995** [comment]
> 
今天上线发现 3.0.5版本的在代码里获取渠道信息的包也有问题,
魅族测试没通过报的是同样的错误
我把错误信息贴到这里您看下


[{"brandName":"魅族","failMsg":"// CRASH: com.zgczw.chezhiwang (pid 16845)\n// Short Msg: java.lang.NoSuchMethodError\n// Long Msg: java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)\n// Build Label: Meizu/meizu_M1852_CN/M1852:8.1.0/OPM1.171019.026/1592244368:user/release-keys\n// Build Changelist: 1592244368\n// Build Time: 1664102963000\n// java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)\n// \tat com.tencent.vasdolly.common.apk.ZipUtils.findZipEndOfCentralDirectoryRecord(ZipUtils.java:12)\n// \tat com.tencent.vasdolly.common.apk.ZipUtils.findZipEndOfCentralDirectoryRecord(ZipUtils.java:2)\n// \tat com.tencent.vasdolly.common.apk.ApkSigningBlockUtils.getEocd(ApkSigningBlockUtils.java:1)\n// \tat com.tencent.vasdolly.common.V2SchemeUtil.getApkSigningBlock(V2SchemeUtil.java:3)\n// \tat com.tencent.vasdolly.reader.IdValueReader.getAllIdValueMap(IdValueReader.java:2)\n// \tat com.tencent.vasdolly.reader.IdValueReader.getByteBufferValueById(IdValueReader.java:2)\n// \tat com.tencent.vasdolly.reader.IdValueReader.getByteValueById(IdValueReader.java:2)\n// \tat com.tencent.vasdolly.reader.IdValueReader.getStringValueById(IdValueReader.java:2)\n// \tat com.tencent.vasdolly.reader.ChannelReader.getChannelByV2(ChannelReader.java:2)\n// \tat com.tencent.vasdolly.helper.ChannelReaderUtil.getChannelByV2(ChannelReaderUtil.java:2)\n// \tat com.tencent.vasdolly.helper.ChannelReaderUtil.getChannel(ChannelReaderUtil.java:2)\n// \tat c.a0.d.p.b.a(ShareUtils.java:1)\n// \tat c.a0.d.p.b.b(ShareUtils.java:1)\n// \tat com.zgczw.chezhiwang.WelcomeActivity.initUM(WelcomeActivity.java:1)\n// \tat com.zgczw.chezhiwang.WelcomeActivity.access$100(WelcomeActivity.java:1)\n// \tat com.zgczw.chezhiwang.WelcomeActivity$a.onClick(WelcomeActivity.java:2)\n// \tat c.a0.d.o.f.b.z.d(PrivacyDialog.java:2)\n// \tat c.a0.d.o.f.b.z.e(Unknown Source:0)\n// \tat c.a0.d.o.f.b.p.onClick(Unknown Source:2)\n// \tat android.view.View.performClick(View.java:6355)\n// \tat android.view.View$PerformClick.run(View.java:25007)\n// \tat android.os.Handler.handleCallback(Handler.java:790)\n// \tat android.os.Handler.dispatchMessage(Handler.java:99)\n// \tat android.os.Looper.loop(Looper.java:192)\n// \tat android.app.ActivityThread.main(ActivityThread.java:6825)\n// \tat java.lang.reflect.Method.invoke(Native Method)\n// \tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)\n// \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)\n// \n","modelName":"meizu_M1852_CN","osVersion":"Flyme 8.1.8.0A"}]

**Comment by yanyongshan** [comment]
麻烦试试3.0.6看是否已经解决

**Comment by realityJie** [comment]
> 麻烦试试3.0.6看是否已经解决

还是会奔溃，幸好上线前发现，不然包发出去，就捅出大窟窿了
