### ISSUE TITLE
不兼容 AGP 3.5.0 生成的 APK: generateV2ChannelApk error

### ISSUE THREAD

**Issue by drakeet** [Tencent/VasDolly#94]
你好，这是一个很棒的项目！但最近我在使用这个工具时，当使用命令行工具对于 AGP 3.5.0 生成的 APK 进行写入渠道，命令行输出如下错误结果：

```
...
generateV2ChannelApk , ./foo.apk add channel success
verified : false
generateV2ChannelApk error , please check it and fix it ，and that you should generate all V2 Channel Apk again!
java.lang.RuntimeException: generateV2ChannelApk , after add channel , ./foo.apk v1 verify failure
	at com.leon.channel.command.Util.generateV2ChannelApk(Util.java:254)
	at com.leon.channel.command.Util.writeChannel(Util.java:108)
	at com.leon.channel.command.Main.main(Main.java:175)
------ File foo.apk generate v2 channel apk , end ------
------ total * channel apk , cost : 199 ------
```

麻烦看下能否解决它，非常感谢！

**Comment by godisnoone** [comment]
遇到同样的问题，apksigner改用build-tools/28.0.3下的后正常了

**Comment by ltlovezh** [comment]
好的，我测试修复下，感谢反馈

**Comment by hqzhon** [comment]
我也遇到同样的问题了，将项目中verify模块的com.android.tools.build:apksig插件更新到3.5.1版本，重新编译产生jar，然后执行命令行正常了

**Comment by vincgao** [comment]
#99 

遇到了同样问题，把 apksig 升到 3.6.1 。同时自己编译了 jar。

**Comment by yanyongshan** [comment]
升级到AGP4.2以上，同时升级VasDolly到3.0.0
